# Generated by Django 4.1.1 on 2022-09-30 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 50, 41, 352698), verbose_name='Дата/время измерения'),
        ),
    ]
