# Generated by Django 4.1.1 on 2022-09-30 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sens_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 16, 9, 37, 881580, tzinfo=datetime.timezone.utc), verbose_name='Дата/время измерения'),
        ),
    ]
